name: Test WordPress Image

on:
  push:
    branches:
      - main

jobs:
  test-wordpress:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "axeman100" | docker login --username percy7 --password-stdin

      - name: Pull the WordPress Image
        run: docker pull percy7/wordpress:6.2.2-apache

      - name: Run the WordPress Container
        run: docker run --name some-wordpress -d percy7/wordpress:6.2.2-apache

      - name: Check if the Container is Running
        run: docker ps | grep some-wordpress